apiVersion: apps/v1
kind: Deployment
metadata:
  name: multipod-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: multipod-app
  template:
    metadata:
      labels:
        app: multipod-app
    spec:
      containers:
        - name: httpd-container
          image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
#          image: image-registry.openshift-image-registry.svc:5000/openshift/java        
          command: ["sleep", "4800"]
        - name: nginx-container
          image: image-registry.openshift-image-registry.svc:5000/openshift/nginx:latest
          command: ["sleep", "4800"]
